-- 
CREATE TABLE ChiTietHoaDon (
  MaChiTietHoaDon INT AUTO_INCREMENT PRIMARY KEY,
  MaSanPham INT,
  SoLuong BIGINT,
  MaHoaDon INT,
  CONSTRAINT FK_ChiTietHoaDon_HoaDon FOREIGN KEY (MaHoaDon) REFERENCES HoaDon(MaHoaDon),
  CONSTRAINT FK_ChiTietHoaDon_SanPham FOREIGN KEY (MaSanPham) REFERENCES SanPham(MaSanPham)
);

CREATE TABLE DoiTuongSD (
  MaDoiTuongSD INT PRIMARY KEY,
  TenDoiTuongSD VARCHAR(50)
);

CREATE TABLE DonDatHang (
  MaHoaDon INT,
  HoVaTen CLOB,
  DiaChi CLOB,
  SDT CLOB,
  TongTien BIGINT,
  MaDonDatHang INT AUTO_INCREMENT PRIMARY KEY,
  TinhTrang BOOLEAN,
  CONSTRAINT FK_DonDatHang_HoaDon FOREIGN KEY (MaHoaDon) REFERENCES HoaDon(MaHoaDon)
);

CREATE TABLE HoaDon (
  MaHoaDon INT AUTO_INCREMENT PRIMARY KEY,
  MaNguoiDung INT,
  NgayMua TIMESTAMP,
  DaMua BOOLEAN,
  CONSTRAINT FK_HoaDon_NguoiDung FOREIGN KEY (MaNguoiDung) REFERENCES NguoiDung(MaNguoiDung)
);

CREATE TABLE NguoiDung (
  MaNguoiDung INT AUTO_INCREMENT PRIMARY KEY,
  TenNguoiDung CLOB,
  TenDangNhap VARCHAR(50),
  MatKhau VARCHAR(50),
  Quyen BOOLEAN
);

CREATE TABLE NhaSanXuat (
  MaNSX INT AUTO_INCREMENT PRIMARY KEY,
  TenNSX VARCHAR(50)
);

CREATE TABLE SanPham (
  MaSanPham INT AUTO_INCREMENT PRIMARY KEY,
  TenSanPham CLOB,
  DonGia BIGINT,
  HinhAnh VARCHAR(50),
  LoaiDongHo VARCHAR(50),
  MaNSX INT NOT NULL,
  MaDoiTuongSD INT NOT NULL,
  DaXoa BOOLEAN,
  CONSTRAINT FK_SanPham_DoiTuongSD FOREIGN KEY (MaDoiTuongSD) REFERENCES DoiTuongSD(MaDoiTuongSD),
  CONSTRAINT FK_SanPham_NhaSanXuat FOREIGN KEY (MaNSX) REFERENCES NhaSanXuat(MaNSX)
);
